"""Initial migration

Revision ID: 3c7976a81e7d
Revises: 
Create Date: 2024-10-14 15:37:58.529835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# see https://stackoverflow.com/a/69063829
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c7976a81e7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
