"""Items

Revision ID: b3342e1d1327
Revises: fdf493a81ad6
Create Date: 2024-10-14 16:08:38.040203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# see https://stackoverflow.com/a/69063829
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3342e1d1327'
down_revision: Union[str, None] = 'fdf493a81ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
