"""Items

Revision ID: fdf493a81ad6
Revises: 3c7976a81e7d
Create Date: 2024-10-14 16:06:38.676796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# see https://stackoverflow.com/a/69063829
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdf493a81ad6'
down_revision: Union[str, None] = '3c7976a81e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
