from sqlmodel import SQLModel, Field

class UserBase(SQLModel):
    name: str
    email: str

class UserCreate(UserBase):
    pass

# Database model, database table inferred from class name
# adds the autogenerated id that will be returned by postgres
class User(UserBase, table=True):
    id: int | None = Field(default=None, primary_key=True)

    # table name is actually "users"
    __tablename__: str = "users"


